language: cpp

os:
  - linux
  - osx

sudo: required
dist: xenial

compiler:
  - gcc
  - clang

cache:
   pip: true
   directories:
     - $HOME/opencv/
     - $HOME/darknet/

matrix:
  include:
    - env: TO_TEST=WITH_ROS_AND_ICE

addons:
  apt:
    sources:
      - sourceline: "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main"
        key_url: "http://ha.pool.sks-keyservers.net/pks/lookup?search=0x421C365BD9FF1F717815A3895523BAEEB01FA116&op=get"
      - sourceline: "deb http://zeroc.com/download/Ice/3.6/ubuntu16.04 stable main"
        key_url: "http://keyserver.ubuntu.com/pks/lookup?search=0x5E6DA83306132997&fingerprint=on&hash=on&op=get"
    packages:
      - rapidjson-dev
      - libssl-dev
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      - libboost-program-options-dev
      - libgoogle-glog-dev
      - libyaml-cpp-dev
      - qt5-default
      - libqt5svg5-dev
      - libqt5opengl5-dev
      - ros-kinetic-roscpp
      - ros-kinetic-cv-bridge
      - ros-kinetic-image-transport
      - zeroc-ice-all-runtime
      - zeroc-ice-all-dev
  homebrew:
    update: true
    brewfile: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/qt/bin:$PATH" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://www.python.org/ftp/python/2.7.15/python-2.7.15-macosx10.6.pkg ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -pkg python-2.7.15-macosx10.6.pkg -target / ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}" ; fi
  - if [[ ( "$TRAVIS_OS_NAME" == "linux" ) && ( "$TO_TEST" == "WITH_ROS_AND_ICE" ) ]]; then source /opt/ros/kinetic/setup.bash ; fi
  - sudo pip install numpy
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -x install_opencv.sh ; fi
  - ./install_darknet.sh

before_script:
  - cd DeepLearningSuite
  - mkdir build
  - cd build
  - cmake ..

script: make -j2


after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait bash ../package.sh ; fi    # To run the script in the same shell so as to setup environment variables
  - ls -lh out/*            # Assuming you have some files in out/ that you would like to upload
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - travis_wait bash upload.sh out/*


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
